version = 1

[cca]
name = "periodic"
mod_rate = 1
cwnd_base_0 = 1200
base_to_amplitude_ratio = 0.25
sampling_rate = 5
transferred_metrics = ["cwnd", "acked_byte", "sent_byte", "rtt", "cwnd_base", "lost_byte"]
shallow_buffer_mitigation = false

[out]
out_after = 300
filename = "data_output"

[monitor.units]
cwnd = "byte"
acked_byte = "byte"
sent_byte = "byte"
rtt = "s"
cwnd_base = "byte"
lost_byte = "byte"

[monitor.composition]
in = ["cwnd_base", "cwnd", "sent_byte"]
out = ["cwnd_base", "acked_byte"]
left = ["rtt"]


[provider]
rate_mbit = 10
granularity = 100
iterations=650