version = 1

[cca]
name = "periodic"
mod_rate = 1
cwnd_base_0 = 1200
base_to_amplitude_ratio = 0.25
sampling_rate = 5
metrics = ["congestion_window", "acked_byte", "sent_byte", "rtt_estimate", "cwnd_base"]
units = ["byte", "byte", "byte", "s", "byte"]

[out]
out_after = 300
filename = "data_output"

[provider]
rate_mbit = 10
granularity = 10