[cca]
name = "pulse"                                                                              # has to match cca key
waveform = "sine"                                                                           # waveform of modulation: sine | square | triangle | saw
mod_rate = 1                                                                                # modulation frequency
cwnd_base_0 = 1200                                                                          # initial cwnd size
base_to_amplitude_ratio = 0.25                                                              # alpha
sampling_rate = 5                                                                           
initial_rtt = 0.1                                                                           #needs to be set to prevent algo from terminating INCREASE                
transferred_metrics = ["cwnd", "acked_byte", "sent_byte", "rtt", "lost_byte", "cwnd_base"]  # timestamp metrics
shallow_buffer_mitigation = false
phi = 0.05                                                                                  # growth scalar
increase_percentile = 25                                                                    # percentile treated a Rref in INCREASE
 
[out]                                                                                      
out_after = 60                                                                              # streaming mode: dumps logs after X seconds
filename = "single_file_test_0"

[monitor.units]
cwnd = "byte"
acked_byte = "byte"
sent_byte = "byte"
rtt = "s"
cwnd_base = "byte"
lost_byte = "byte"

[monitor.composition]
in = ["cwnd_base", "cwnd", "sent_byte"]
out = ["cwnd_base", "acked_byte"]
left = ["rtt"]


[provider]
single_file_mode = true
single_file_size_mbit = 1000

#streaming mode
rate_mbit = 10
granularity = 100
iterations=650