version = 1

[cca]
name = "pulse"
mod_rate = 1
cwnd_base_0 = 1200
base_to_amplitude_ratio = 0.25
sampling_rate = 5
initial_rtt = 0.1 #needs to be set to prevent algo from terminating INCREASE
transferred_metrics = ["cwnd", "acked_byte", "sent_byte", "rtt", "lost_byte", "cwnd_base"]
shallow_buffer_mitigation = false
phi = 0.05
increase_percentile = 25

[out]
out_after = 60
filename = "single_file_test_0"

[monitor.units]
cwnd = "byte"
acked_byte = "byte"
sent_byte = "byte"
rtt = "s"
cwnd_base = "byte"
lost_byte = "byte"

[monitor.composition]
in = ["cwnd_base", "cwnd", "sent_byte"]
out = ["cwnd_base", "acked_byte"]
left = ["rtt"]


[provider]
single_file_mode = true
single_file_size_mbit = 500

rate_mbit = 10
granularity = 100
iterations=650